export const mock = [
	{
		id: 1,
		imgUrl: 'url',
		person: 'Hakio',
		title: 'a écrit un nouvel article.',
		titleIcon: true,
		description: 'Sur “Sortie de Monster Hunter World”',
		datePublish: '30 mars 2020',
	},
	{
		id: 2,
		imgUrl: 'url',
		title: 'Sortie de Monster Hunter World',
		description: 'Sur',
		descriptionIcon: true,
		descriptionLink: 'Monster Hunter World',
		datePublish: '29 mars 2020',
	},
	{
		id: 3,
		imgUrl: 'url',
		person: 'Hakio',
		title: 'a écrit un nouvel avis.',
		icon: true,
		titleIcon: true,
		description: 'Sur Monster Hunter World',
		datePublish: '28 mars 2020',
	},
	{
		id: 4,
		imgUrl: 'url',
		title: 'J-7 avant la sortie de Monster Hunter World',
		descriptionIcon: true,
		descriptionLink: 'Monster Hunter World',
		datePublish: '28 mars 2020',
	},
	{
		id: 5,
		imgUrl: 'url',
		title: 'Sortie de Monster Hunter World !',
		descriptionIcon: true,
		descriptionLink: 'Monster Hunter World',
		datePublish: '28 mars 2020',
	},
	{
		id: 6,
		imgUrl: 'url',
		person: 'Hakio',
		title: 'est en live !',
		titleIcon: true,
		description: 'Sur Monster Hunter World',
		datePublish: '28 mars 2020',
	},
	{
		id: 7,
		imgUrl: 'url',
		person: 'Hakio',
		title: 'a publié une vidéo.',
		titleIcon: true,
		description: '“On part en mer sur Sea of Thieves”',
		datePublish: '28 mars 2020',
	},
	{
		id: 8,
		imgUrl: 'url',
		person: 'Hakio',
		title: 'a publié une illustration.',
		titleIcon: true,
		description: '“FanArt de World of Warcraft”',
		datePublish: '22 mars 2020',
	},
	{
		id: 9,
		imgUrl: 'url',
		person: 'Hakio',
		title: 'a publié un Cosplay.',
		titleIcon: true,
		description: '“Cosplay Ahri”',
		datePublish: '22 mars 2020',
	},
	{
		id: 10,
		imgUrl: 'url',
		person: 'Hakio',
		title: 'a ajouté un chapitre à son récit.',
		titleIcon: true,
		description: '“L’histoire insolite du Palais vivant”',
		datePublish: '22 mars 2020',
	},
	{
		id: 11,
		imgUrl: 'url',
		person: 'Hakio',
		title: 'a publié un récit. Découvre-le !',
		titleIcon: true,
		description: '“L’histoire insolite du Palais vivant” ',
		datePublish: '21 mars 2020',
	},
	{
		id: 12,
		imgUrl: 'url',
		person: 'Hakio',
		title: 'a publié une illustration.',
		titleIcon: true,
		description: 'N’hésite pas à venir partager avec la commu’',
		datePublish: '30 mars 2020',
		disable: true,
	},
	{
		id: 13,
		imgUrl: 'url',
		title: 'Un jeu Fast and Furious annoncé',
		description: 'Sur',
		descriptionLink: 'Fast and Furious',
		datePublish: '22 mars 2020',
		disable: true,
	},
];
